"""consultant exchange profile

Revision ID: 0015_consultant_exchange_profile
Revises: 0014_mock_role_scope
Create Date: 2026-05-17
"""
from alembic import op
import sqlalchemy as sa


revision = "0015_consultant_exchange_profile"
down_revision = "0014_mock_role_scope"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("consultant_profiles", sa.Column("preferred_name", sa.String(length=120), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("linkedin_url", sa.String(length=500), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("relocation_preference", sa.String(length=160), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("onsite_preference", sa.String(length=120), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("visa_valid_until", sa.String(length=40), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("ead_valid_until", sa.String(length=40), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("target_industry_domain", sa.String(length=120), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("marketing_status", sa.String(length=80), nullable=False, server_default="profile_intake"))
    op.add_column("consultant_profiles", sa.Column("professional_experience", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("domain_experience", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("certifications", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("education_summary", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("base_resume_reference", sa.String(length=500), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("latest_project_title", sa.String(length=220), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("latest_project_domain", sa.String(length=120), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("latest_project_summary", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("resume_readiness_score", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("consultant_profiles", sa.Column("technical_readiness_score", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("consultant_profiles", sa.Column("interview_readiness_score", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("consultant_profiles", sa.Column("communication_score", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("consultant_profiles", sa.Column("profile_intake_complete", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("education_verified", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("certifications_verified", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("experience_verified", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("base_resume_received", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("resume_tailoring_complete", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("latest_project_updated", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("project_story_validated", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("training_plan_assigned", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("glossary_review_complete", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("mock_interview_passed", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("marketing_brief_ready", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("consultant_profiles", sa.Column("checklist_notes", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("rate_expectation", sa.String(length=80), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("staff_owner", sa.String(length=160), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("recruiter_owner", sa.String(length=160), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("profile_strengths", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("profile_gaps", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("marketing_notes", sa.Text(), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("maas_profile_id", sa.String(length=120), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("maas_sync_status", sa.String(length=80), nullable=False, server_default="not_synced"))
    op.add_column("consultant_profiles", sa.Column("maas_last_synced_at", sa.String(length=80), nullable=False, server_default=""))
    op.add_column("consultant_profiles", sa.Column("maas_payload_notes", sa.Text(), nullable=False, server_default=""))
    op.create_index("ix_consultant_profiles_marketing_status", "consultant_profiles", ["marketing_status"])
    op.create_index("ix_consultant_profiles_maas_profile_id", "consultant_profiles", ["maas_profile_id"])


def downgrade() -> None:
    op.drop_index("ix_consultant_profiles_maas_profile_id", table_name="consultant_profiles")
    op.drop_index("ix_consultant_profiles_marketing_status", table_name="consultant_profiles")
    op.drop_column("consultant_profiles", "maas_payload_notes")
    op.drop_column("consultant_profiles", "maas_last_synced_at")
    op.drop_column("consultant_profiles", "maas_sync_status")
    op.drop_column("consultant_profiles", "maas_profile_id")
    op.drop_column("consultant_profiles", "marketing_notes")
    op.drop_column("consultant_profiles", "profile_gaps")
    op.drop_column("consultant_profiles", "profile_strengths")
    op.drop_column("consultant_profiles", "recruiter_owner")
    op.drop_column("consultant_profiles", "staff_owner")
    op.drop_column("consultant_profiles", "rate_expectation")
    op.drop_column("consultant_profiles", "checklist_notes")
    op.drop_column("consultant_profiles", "marketing_brief_ready")
    op.drop_column("consultant_profiles", "mock_interview_passed")
    op.drop_column("consultant_profiles", "glossary_review_complete")
    op.drop_column("consultant_profiles", "training_plan_assigned")
    op.drop_column("consultant_profiles", "project_story_validated")
    op.drop_column("consultant_profiles", "latest_project_updated")
    op.drop_column("consultant_profiles", "resume_tailoring_complete")
    op.drop_column("consultant_profiles", "base_resume_received")
    op.drop_column("consultant_profiles", "experience_verified")
    op.drop_column("consultant_profiles", "certifications_verified")
    op.drop_column("consultant_profiles", "education_verified")
    op.drop_column("consultant_profiles", "profile_intake_complete")
    op.drop_column("consultant_profiles", "communication_score")
    op.drop_column("consultant_profiles", "interview_readiness_score")
    op.drop_column("consultant_profiles", "technical_readiness_score")
    op.drop_column("consultant_profiles", "resume_readiness_score")
    op.drop_column("consultant_profiles", "latest_project_summary")
    op.drop_column("consultant_profiles", "latest_project_domain")
    op.drop_column("consultant_profiles", "latest_project_title")
    op.drop_column("consultant_profiles", "base_resume_reference")
    op.drop_column("consultant_profiles", "education_summary")
    op.drop_column("consultant_profiles", "certifications")
    op.drop_column("consultant_profiles", "domain_experience")
    op.drop_column("consultant_profiles", "professional_experience")
    op.drop_column("consultant_profiles", "marketing_status")
    op.drop_column("consultant_profiles", "target_industry_domain")
    op.drop_column("consultant_profiles", "ead_valid_until")
    op.drop_column("consultant_profiles", "visa_valid_until")
    op.drop_column("consultant_profiles", "onsite_preference")
    op.drop_column("consultant_profiles", "relocation_preference")
    op.drop_column("consultant_profiles", "linkedin_url")
    op.drop_column("consultant_profiles", "preferred_name")
